services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: produits

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

